on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Github release version and build.gradle version match
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          if [[ $(./gradlew -q printVersion) != "${RELEASE_TAG_NAME:1}" ]]
            then
              echo "Release tag (${RELEASE_TAG_NAME:1}) does not match the build.gradle version"
              exit 1
          fi
          echo "Release tag matches the build.gradle version. Proceeding with publish_release workflow."

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Publish com.withabound.withabound-java
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Close and release com.withabound.withabound-java
        run: |
          if ./gradlew -q printVersion | grep -q "SNAPSHOT"; then
            echo "This is a SNAPSHOT release — exiting early and not invoking ./gradlew closeAndReleaseRepository"
            exit 0
          fi

          if ! ./gradlew closeAndReleaseRepository --stacktrace; then
            echo "🛑🛑🛑"
            echo "Publish to Nexus Sonatype succeeded, but failed to close and release. This step assumes there
            is only one staging repository active when it is called. Stale staging repositories may need
            to be purged manually before proceeding. They can be removed by logging into
            https://s01.oss.sonatype.org/."
            echo "🛑🛑🛑"
            exit 1
          fi
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Send Slack notification
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          text: "com.withabound/withabound-java@${{ steps.npm-publish.outputs.version }} has been published."
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SUCCESS_DEPLOYMENT_PRODUCT_URL }}

      # Upon completion of the release step, OSSRH will sync components to Maven Central typically within
      # 30 minutes, though updates to search may take up to four hours.
      # Ref https://central.sonatype.org/publish/publish-guide/#releasing-to-central
